
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module mcu(

	//////////// CLOCK //////////
	input CLK,

	//////////// 7-segment decoder //////////
	output [6:0] HEX0,
	output [6:0] HEX1,
	output [6:0] HEX2,
	output [6:0] HEX3,
	
	//////////// LED /////////////
	output [9:0] LED,
	
	//////////// SWITCH //////////
	input [9:0] SW,
	
	//////////// BUTTON //////////
	input [2:0] BTN
	
);
//*******************************//

// add module here
assign clk = BTN[1];
assign rst = ~BTN[0];
logic [7:0]portb_out;

// add module here
cpu c0(
	.clk(CLK),
	.rst(rst),
	.port_b_out(portb_out)
);
seven_decoder decoder0(//第一個HEX
	.A(portb_out[7:4]),
	.y(HEX1)
);
seven_decoder decoder1(//第二個HEX
	.A(portb_out[3:0]),
	.y(HEX0)
);
//*******************************//

endmodule
